"""Add title to Messages

Revision ID: c411f3e91be1
Revises: 
Create Date: 2025-09-03 10:33:54.761714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c411f3e91be1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('scheduled_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('degree_type_target', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('location_target', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('stage_target', sa.String(length=30), nullable=True))
        batch_op.alter_column('degreeCode',
               existing_type=sa.VARCHAR(length=8),
               nullable=True)
        batch_op.alter_column('week_released',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Messages', schema=None) as batch_op:
        batch_op.alter_column('week_released',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('degreeCode',
               existing_type=sa.VARCHAR(length=8),
               nullable=False)
        batch_op.drop_column('stage_target')
        batch_op.drop_column('location_target')
        batch_op.drop_column('degree_type_target')
        batch_op.drop_column('scheduled_at')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
