"""Fix Admin table column name from permissionName to permission_name

Revision ID: fix_admin_column_name
Revises: c411f3e91be1
Create Date: 2025-09-30 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fix_admin_column_name'
down_revision = 'c411f3e91be1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Admin', schema=None) as batch_op:
        # Add new column with correct name
        batch_op.add_column(sa.Column('permission_name', sa.String(length=50), nullable=False, server_default=''))
        
    # Copy data from old column to new column
    op.execute("UPDATE Admin SET permission_name = permissionName")
    
    with op.batch_alter_table('Admin', schema=None) as batch_op:
        # Remove old column
        batch_op.drop_column('permissionName')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Admin', schema=None) as batch_op:
        # Add back old column
        batch_op.add_column(sa.Column('permissionName', sa.VARCHAR(length=50), nullable=False, server_default=''))
        
    # Copy data back
    op.execute("UPDATE Admin SET permissionName = permission_name")
    
    with op.batch_alter_table('Admin', schema=None) as batch_op:
        # Remove new column
        batch_op.drop_column('permission_name')
    # ### end Alembic commands ###